import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/resources',
        'core-concepts/relationships',
        'core-concepts/auth',
        'core-concepts/uploads',
        'core-concepts/search-filter',
        'core-concepts/api-gateway',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/custom-actions',
        'guides/validation-errors',
        'guides/llm-integration',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contributing',
      ],
    },
  ],
};

export default sidebars;
